version: "3"  # optional since v1.27.0
services:
  squint:
    profiles:
      - "server"
    ports:
      - "6749:6749"
    build:
      context: ./
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    image: docker.io/postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  pgdata: